#ifndef J1939_TX_FSM_PRIVATE_H
#define J1939_TX_FSM_PRIVATE_H

#include "j1939_tx_fsm_enums.h"
#include "j1939_tx_fsm.h"

unsigned char j1939_tx_fsm_table[][20] = {
                                                             /*transmit_rts_j1939_signal wait_rts_transmit_confirm_j1939_signal, wait_cts_j1939_signal, receive_cts_j1939_signal, transmit_dt_j1939_signal, wait_dt_transmit_confirm_j1939_signal, wait_end_of_msg_ack_j1939_signal, receive_end_of_msg_ack_j1939_signal, receive_conn_abort_timeout_j1939_signal, receive_conn_abort_resources_end_j1939_signal, tx_conn_abort_timeout_j1939_signal,        wait_tx_conn_abort_timeout_j1939_signal, tx_conn_abort_resources_end_j1939_signal,         wait_tx_conn_abort_resources_end_j1939_signal, default_j1939_signal, transmit_first_bam_j1939_signal, transmit_data_bam_j1939_signal, wait_first_bam_transmit_confirm_j1939_signal, wait_data_bam_transmit_confirm_j1939_signal, timeout_j1939_signal*/
/* TX_DEFAULT_J1939 */ {                                             TRANSMIT_RTS_J1939,                        TX_IGNORE_J1939,       TX_IGNORE_J1939,          TX_IGNORE_J1939,          TX_IGNORE_J1939,                       TX_IGNORE_J1939,                  TX_IGNORE_J1939,                     TX_IGNORE_J1939,                         TX_IGNORE_J1939,                               TX_IGNORE_J1939,                    TX_IGNORE_J1939,                                TX_IGNORE_J1939,                          TX_IGNORE_J1939,                                       TX_IGNORE_J1939,      TX_IGNORE_J1939,              TRANSMIT_FIRST_BAM,                TX_IGNORE_J1939,                              TX_IGNORE_J1939,                             TX_IGNORE_J1939,      TX_IGNORE_J1939 },
/* TRANSMIT_RTS_J1939 */ {                                           TRANSMIT_RTS_J1939,        WAIT_RTS_TRANSMIT_CONFIRM_J1939,       TX_IGNORE_J1939,          TX_IGNORE_J1939,          TX_IGNORE_J1939,                       TX_IGNORE_J1939,                  TX_IGNORE_J1939,                     TX_IGNORE_J1939,              RECEIVE_CONN_ABORT_TIMEOUT,              RECEIVE_CONN_ABORT_RESOURCES_END,                    TX_IGNORE_J1939,                                TX_IGNORE_J1939,                          TX_IGNORE_J1939,                                       TX_IGNORE_J1939,      TX_IGNORE_J1939,                 TX_IGNORE_J1939,                TX_IGNORE_J1939,                              TX_IGNORE_J1939,                             TX_IGNORE_J1939,      TX_IGNORE_J1939 },
/* WAIT_RTS_TRANSMIT_CONFIRM_J1939 */ {                              TRANSMIT_RTS_J1939,                        TX_IGNORE_J1939,        WAIT_CTS_J1939,        RECEIVE_CTS_J1939,          TX_IGNORE_J1939,                       TX_IGNORE_J1939,                  TX_IGNORE_J1939,                     TX_IGNORE_J1939,              RECEIVE_CONN_ABORT_TIMEOUT,              RECEIVE_CONN_ABORT_RESOURCES_END,        TRANSMIT_CONN_ABORT_TIMEOUT,                                TX_IGNORE_J1939,        TRANSMIT_CONN_ABORT_RESOURCES_END,                                       TX_IGNORE_J1939,      TX_IGNORE_J1939,                 TX_IGNORE_J1939,                TX_IGNORE_J1939,                              TX_IGNORE_J1939,                             TX_IGNORE_J1939,      TX_IGNORE_J1939 },
/* WAIT_CTS_J1939 */ {                                               TRANSMIT_RTS_J1939,                        TX_IGNORE_J1939,       TX_IGNORE_J1939,        RECEIVE_CTS_J1939,          TX_IGNORE_J1939,                       TX_IGNORE_J1939,                  TX_IGNORE_J1939,                     TX_IGNORE_J1939,              RECEIVE_CONN_ABORT_TIMEOUT,              RECEIVE_CONN_ABORT_RESOURCES_END,        TRANSMIT_CONN_ABORT_TIMEOUT,                                TX_IGNORE_J1939,        TRANSMIT_CONN_ABORT_RESOURCES_END,                                       TX_IGNORE_J1939,      TX_IGNORE_J1939,                 TX_IGNORE_J1939,                TX_IGNORE_J1939,                              TX_IGNORE_J1939,                             TX_IGNORE_J1939,      TX_IGNORE_J1939 },
/* RECEIVE_CTS_J1939 */ {                                            TRANSMIT_RTS_J1939,                        TX_IGNORE_J1939,       TX_IGNORE_J1939,          TX_IGNORE_J1939,              TRANSMIT_DT,                       TX_IGNORE_J1939,                  TX_IGNORE_J1939,                     TX_IGNORE_J1939,              RECEIVE_CONN_ABORT_TIMEOUT,              RECEIVE_CONN_ABORT_RESOURCES_END,                    TX_IGNORE_J1939,                                TX_IGNORE_J1939,                          TX_IGNORE_J1939,                                       TX_IGNORE_J1939,      TX_IGNORE_J1939,                 TX_IGNORE_J1939,                TX_IGNORE_J1939,                              TX_IGNORE_J1939,                             TX_IGNORE_J1939,      TX_IGNORE_J1939 },
/* TRANSMIT_DT */ {                                                  TRANSMIT_RTS_J1939,                        TX_IGNORE_J1939,       TX_IGNORE_J1939,          TX_IGNORE_J1939,          TX_IGNORE_J1939,        WAIT_DT_TRANSMIT_CONFIRM_J1939,                  TX_IGNORE_J1939,                     TX_IGNORE_J1939,              RECEIVE_CONN_ABORT_TIMEOUT,              RECEIVE_CONN_ABORT_RESOURCES_END,                    TX_IGNORE_J1939,                                TX_IGNORE_J1939,                          TX_IGNORE_J1939,                                       TX_IGNORE_J1939,      TX_IGNORE_J1939,                 TX_IGNORE_J1939,                TX_IGNORE_J1939,                              TX_IGNORE_J1939,                             TX_IGNORE_J1939,      TX_IGNORE_J1939 },
/* WAIT_DT_TRANSMIT_CONFIRM_J1939 */ {                               TRANSMIT_RTS_J1939,                        TX_IGNORE_J1939,        WAIT_CTS_J1939,        RECEIVE_CTS_J1939,              TRANSMIT_DT,                       TX_IGNORE_J1939,           WAIT_RX_END_OF_MSG_ACK,              RECEIVE_END_OF_MSG_ACK,              RECEIVE_CONN_ABORT_TIMEOUT,              RECEIVE_CONN_ABORT_RESOURCES_END,        TRANSMIT_CONN_ABORT_TIMEOUT,                                TX_IGNORE_J1939,                          TX_IGNORE_J1939,                                       TX_IGNORE_J1939,      TX_IGNORE_J1939,                 TX_IGNORE_J1939,                TX_IGNORE_J1939,                              TX_IGNORE_J1939,                             TX_IGNORE_J1939,      TX_IGNORE_J1939 },
/* WAIT_RX_END_OF_MSG_ACK */ {                                       TRANSMIT_RTS_J1939,                        TX_IGNORE_J1939,       TX_IGNORE_J1939,          TX_IGNORE_J1939,          TX_IGNORE_J1939,                       TX_IGNORE_J1939,                  TX_IGNORE_J1939,              RECEIVE_END_OF_MSG_ACK,              RECEIVE_CONN_ABORT_TIMEOUT,              RECEIVE_CONN_ABORT_RESOURCES_END,        TRANSMIT_CONN_ABORT_TIMEOUT,                                TX_IGNORE_J1939,                          TX_IGNORE_J1939,                                       TX_IGNORE_J1939,      TX_IGNORE_J1939,                 TX_IGNORE_J1939,                TX_IGNORE_J1939,                              TX_IGNORE_J1939,                             TX_IGNORE_J1939,      TX_IGNORE_J1939 },
/* RECEIVE_END_OF_MSG_ACK */ {                                       TRANSMIT_RTS_J1939,                        TX_IGNORE_J1939,       TX_IGNORE_J1939,          TX_IGNORE_J1939,          TX_IGNORE_J1939,                       TX_IGNORE_J1939,                  TX_IGNORE_J1939,                     TX_IGNORE_J1939,                         TX_IGNORE_J1939,                               TX_IGNORE_J1939,                    TX_IGNORE_J1939,                                TX_IGNORE_J1939,                          TX_IGNORE_J1939,                                       TX_IGNORE_J1939,     TX_DEFAULT_J1939,                 TX_IGNORE_J1939,                TX_IGNORE_J1939,                              TX_IGNORE_J1939,                             TX_IGNORE_J1939,      TX_IGNORE_J1939 },
/* RECEIVE_CONN_ABORT_TIMEOUT */ {                                   TRANSMIT_RTS_J1939,                        TX_IGNORE_J1939,       TX_IGNORE_J1939,          TX_IGNORE_J1939,          TX_IGNORE_J1939,                       TX_IGNORE_J1939,                  TX_IGNORE_J1939,                     TX_IGNORE_J1939,                         TX_IGNORE_J1939,                               TX_IGNORE_J1939,                    TX_IGNORE_J1939,                                TX_IGNORE_J1939,                          TX_IGNORE_J1939,                                       TX_IGNORE_J1939,     TX_DEFAULT_J1939,                 TX_IGNORE_J1939,                TX_IGNORE_J1939,                              TX_IGNORE_J1939,                             TX_IGNORE_J1939,      TX_IGNORE_J1939 },
/* RECEIVE_CONN_ABORT_RESOURCES_END */ {                             TRANSMIT_RTS_J1939,                        TX_IGNORE_J1939,       TX_IGNORE_J1939,          TX_IGNORE_J1939,          TX_IGNORE_J1939,                       TX_IGNORE_J1939,                  TX_IGNORE_J1939,                     TX_IGNORE_J1939,                         TX_IGNORE_J1939,                               TX_IGNORE_J1939,                    TX_IGNORE_J1939,                                TX_IGNORE_J1939,                          TX_IGNORE_J1939,                                       TX_IGNORE_J1939,     TX_DEFAULT_J1939,                 TX_IGNORE_J1939,                TX_IGNORE_J1939,                              TX_IGNORE_J1939,                             TX_IGNORE_J1939,      TX_IGNORE_J1939 },
/* TRANSMIT_CONN_ABORT_TIMEOUT */ {                                  TRANSMIT_RTS_J1939,                        TX_IGNORE_J1939,       TX_IGNORE_J1939,          TX_IGNORE_J1939,          TX_IGNORE_J1939,                       TX_IGNORE_J1939,                  TX_IGNORE_J1939,                     TX_IGNORE_J1939,                         TX_IGNORE_J1939,                               TX_IGNORE_J1939,                    TX_IGNORE_J1939, WAIT_CONN_ABORT_TIMEOUT_TRANSMIT_CONFIRM_J1939,                          TX_IGNORE_J1939,                                       TX_IGNORE_J1939,      TX_IGNORE_J1939,                 TX_IGNORE_J1939,                TX_IGNORE_J1939,                              TX_IGNORE_J1939,                             TX_IGNORE_J1939,      TX_IGNORE_J1939 },
/* WAIT_CONN_ABORT_TIMEOUT_TRANSMIT_CONFIRM_J1939 */ {               TRANSMIT_RTS_J1939,                        TX_IGNORE_J1939,       TX_IGNORE_J1939,          TX_IGNORE_J1939,          TX_IGNORE_J1939,                       TX_IGNORE_J1939,                  TX_IGNORE_J1939,                     TX_IGNORE_J1939,                         TX_IGNORE_J1939,                               TX_IGNORE_J1939,                    TX_IGNORE_J1939,                                TX_IGNORE_J1939,                          TX_IGNORE_J1939,                                       TX_IGNORE_J1939,     TX_DEFAULT_J1939,                 TX_IGNORE_J1939,                TX_IGNORE_J1939,                              TX_IGNORE_J1939,                             TX_IGNORE_J1939,      TX_IGNORE_J1939 },
/* TRANSMIT_CONN_ABORT_RESOURCES_END */ {                            TRANSMIT_RTS_J1939,                        TX_IGNORE_J1939,       TX_IGNORE_J1939,          TX_IGNORE_J1939,          TX_IGNORE_J1939,                       TX_IGNORE_J1939,                  TX_IGNORE_J1939,                     TX_IGNORE_J1939,                         TX_IGNORE_J1939,                               TX_IGNORE_J1939,                    TX_IGNORE_J1939,                                TX_IGNORE_J1939,                          TX_IGNORE_J1939,  WAIT_CONN_ABORT_RESOURCES_END_TRANSMIT_CONFIRM_J1939,      TX_IGNORE_J1939,                 TX_IGNORE_J1939,                TX_IGNORE_J1939,                              TX_IGNORE_J1939,                             TX_IGNORE_J1939,      TX_IGNORE_J1939 },
/*  WAIT_CONN_ABORT_RESOURCES_END_TRANSMIT_CONFIRM_J1939 */ {        TRANSMIT_RTS_J1939,                        TX_IGNORE_J1939,       TX_IGNORE_J1939,          TX_IGNORE_J1939,          TX_IGNORE_J1939,                       TX_IGNORE_J1939,                  TX_IGNORE_J1939,                     TX_IGNORE_J1939,                         TX_IGNORE_J1939,                               TX_IGNORE_J1939,                    TX_IGNORE_J1939,                                TX_IGNORE_J1939,                          TX_IGNORE_J1939,                                       TX_IGNORE_J1939,     TX_DEFAULT_J1939,                 TX_IGNORE_J1939,                TX_IGNORE_J1939,                              TX_IGNORE_J1939,                             TX_IGNORE_J1939,      TX_IGNORE_J1939 },
/* TRANSMIT_FIRST_BAM */ {                                              TX_IGNORE_J1939,                        TX_IGNORE_J1939,       TX_IGNORE_J1939,          TX_IGNORE_J1939,          TX_IGNORE_J1939,                       TX_IGNORE_J1939,                  TX_IGNORE_J1939,                     TX_IGNORE_J1939,                         TX_IGNORE_J1939,                               TX_IGNORE_J1939,                    TX_IGNORE_J1939,                                TX_IGNORE_J1939,                          TX_IGNORE_J1939,                                       TX_IGNORE_J1939,      TX_IGNORE_J1939,                 TX_IGNORE_J1939,                TX_IGNORE_J1939,        WAIT_FIRST_BAM_TRANSMIT_CONFIRM_J1939,                             TX_IGNORE_J1939,      TX_IGNORE_J1939 },
/* TRANSMIT_DATA_BAM */ {                                               TX_IGNORE_J1939,                        TX_IGNORE_J1939,       TX_IGNORE_J1939,          TX_IGNORE_J1939,          TX_IGNORE_J1939,                       TX_IGNORE_J1939,                  TX_IGNORE_J1939,                     TX_IGNORE_J1939,                         TX_IGNORE_J1939,                               TX_IGNORE_J1939,                    TX_IGNORE_J1939,                                TX_IGNORE_J1939,                          TX_IGNORE_J1939,                                       TX_IGNORE_J1939,      TX_IGNORE_J1939,                 TX_IGNORE_J1939,                TX_IGNORE_J1939,                              TX_IGNORE_J1939,        WAIT_DATA_BAM_TRANSMIT_CONFIRM_J1939,      TX_IGNORE_J1939 },
/* WAIT_FIRST_BAM_TRANSMIT_CONFIRM_J1939 */ {                           TX_IGNORE_J1939,                        TX_IGNORE_J1939,       TX_IGNORE_J1939,          TX_IGNORE_J1939,          TX_IGNORE_J1939,                       TX_IGNORE_J1939,                  TX_IGNORE_J1939,                     TX_IGNORE_J1939,                         TX_IGNORE_J1939,                               TX_IGNORE_J1939,                    TX_IGNORE_J1939,                                TX_IGNORE_J1939,                          TX_IGNORE_J1939,                                       TX_IGNORE_J1939,      TX_IGNORE_J1939,                 TX_IGNORE_J1939,              TRANSMIT_DATA_BAM,                              TX_IGNORE_J1939,                             TX_IGNORE_J1939, TIMEOUT_TRANSMIT_BAM },
/* WAIT_DATA_BAM_TRANSMIT_CONFIRM_J1939 */ {                            TX_IGNORE_J1939,                        TX_IGNORE_J1939,       TX_IGNORE_J1939,          TX_IGNORE_J1939,          TX_IGNORE_J1939,                       TX_IGNORE_J1939,                  TX_IGNORE_J1939,                     TX_IGNORE_J1939,                         TX_IGNORE_J1939,                               TX_IGNORE_J1939,                    TX_IGNORE_J1939,                                TX_IGNORE_J1939,                          TX_IGNORE_J1939,                                       TX_IGNORE_J1939,     TX_DEFAULT_J1939,                 TX_IGNORE_J1939,              TRANSMIT_DATA_BAM,                              TX_IGNORE_J1939,                             TX_IGNORE_J1939, TIMEOUT_TRANSMIT_BAM },
/* TIMEOUT_TRANSMIT_BAM */ {                                            TX_IGNORE_J1939,                        TX_IGNORE_J1939,       TX_IGNORE_J1939,          TX_IGNORE_J1939,          TX_IGNORE_J1939,                       TX_IGNORE_J1939,                  TX_IGNORE_J1939,                     TX_IGNORE_J1939,                         TX_IGNORE_J1939,                               TX_IGNORE_J1939,                    TX_IGNORE_J1939,                                TX_IGNORE_J1939,                          TX_IGNORE_J1939,                                       TX_IGNORE_J1939,     TX_DEFAULT_J1939,                 TX_IGNORE_J1939,                TX_IGNORE_J1939,                              TX_IGNORE_J1939,                             TX_IGNORE_J1939,      TX_IGNORE_J1939 }
};

/*!
\brief short description

full description

\param[in]
*/
static enum j1939_tx_state get_tx_j1939_state(struct j1939_tp_s* instance);

/*!
\brief short description

full description

\param[in]
*/
static void set_tx_j1939_signal(struct j1939_tp_s* instance, enum j1939_tx_signal signal);


#endif /* J1939_TX_FSM_PRIVATE_H */
