#ifndef J1939_RX_FSM_PRIVATE_H
#define J1939_RX_FSM_PRIVATE_H

#include "j1939_rx_fsm.h"

unsigned char j1939_rx_fsm_table[][22] = {
                                                            /*rx_rts_j1939_signal tx_cts_j1939_signal, wait_confirm_tx_cts_j1939_signal, tx_confirm_j1939_signal, wait_dt_j1939_signal, rx_data_j1939_signal, tx_end_of_msg_ack_j1939_signal, wait_confirm_tx_end_of_msg_ack, tx_conn_abort_timeout_j1939_signal,  wait_tx_conn_abort_timeout_j1939_signal, tx_conn_abort_resources_end_j1939_signal,  wait_tx_conn_abort_resources_end_j1939_signal, default_j1939_signal, rx_timeout_j1939_signal,  tx_conn_abort_setup_early_j1939_signal,          wait_tx_conn_abort_setup_early_j1939_signal, rx_conn_abort_timeout_j1939_signal, rx_conn_abort_resources_end_j1939_signal, receive_first_bam_j1939_signal, wait_data_bam_j1939_signal, receive_data_bam_j1939_signal, timeout_receive_bam_j1939_signal*/
/* RX_DEFAULT_J1939 */ {                                             RECEIVE_RTS,     RX_IGNORE_J1939,                  RX_IGNORE_J1939,         RX_IGNORE_J1939,      RX_IGNORE_J1939,      RX_IGNORE_J1939,                RX_IGNORE_J1939,                RX_IGNORE_J1939,                    RX_IGNORE_J1939,                          RX_IGNORE_J1939,                          RX_IGNORE_J1939,                                RX_IGNORE_J1939,      RX_IGNORE_J1939,         RX_IGNORE_J1939,                         RX_IGNORE_J1939,                                      RX_IGNORE_J1939,                    RX_IGNORE_J1939,                          RX_IGNORE_J1939,              RECEIVE_FIRST_BAM,            RX_IGNORE_J1939,               RX_IGNORE_J1939,                 RX_IGNORE_J1939 },
/* RECEIVE_RTS */ {                                            UNEXP_RECEIVE_RTS,        TRANSMIT_CTS,                  RX_IGNORE_J1939,         RX_IGNORE_J1939,      RX_IGNORE_J1939,      RX_IGNORE_J1939,                RX_IGNORE_J1939,                RX_IGNORE_J1939,                    RX_IGNORE_J1939,                          RX_IGNORE_J1939,              TX_CONN_ABORT_RESOURCES_END,                                RX_IGNORE_J1939,      RX_IGNORE_J1939,                 TIMEOUT, TRANSMIT_CONN_ABORT_SESSION_SETUP_EARLY,                                      RX_IGNORE_J1939,              RX_CONN_ABORT_TIMEOUT,              RX_CONN_ABORT_RESOURCES_END,                RX_IGNORE_J1939,            RX_IGNORE_J1939,               RX_IGNORE_J1939,                 RX_IGNORE_J1939 },
/* TRANSMIT_CTS */ {                                           UNEXP_RECEIVE_RTS,     RX_IGNORE_J1939,        WAIT_CONFIRM_TRANSMIT_CTS,                 WAIT_DT,      RX_IGNORE_J1939,           RECEIVE_DT,                RX_IGNORE_J1939,                RX_IGNORE_J1939,              TX_CONN_ABORT_TIMEOUT,                          RX_IGNORE_J1939,              TX_CONN_ABORT_RESOURCES_END,                                RX_IGNORE_J1939,      RX_IGNORE_J1939,                 TIMEOUT,                         RX_IGNORE_J1939,                                      RX_IGNORE_J1939,              RX_CONN_ABORT_TIMEOUT,              RX_CONN_ABORT_RESOURCES_END,                RX_IGNORE_J1939,            RX_IGNORE_J1939,               RX_IGNORE_J1939,                 RX_IGNORE_J1939 },
/* WAIT_CONFIRM_TRANSMIT_CTS */ {                              UNEXP_RECEIVE_RTS,     RX_IGNORE_J1939,                  RX_IGNORE_J1939,                 WAIT_DT,      RX_IGNORE_J1939,           RECEIVE_DT,                RX_IGNORE_J1939,                RX_IGNORE_J1939,              TX_CONN_ABORT_TIMEOUT,                          RX_IGNORE_J1939,              TX_CONN_ABORT_RESOURCES_END,                                RX_IGNORE_J1939,      RX_IGNORE_J1939,                 TIMEOUT,                         RX_IGNORE_J1939,                                      RX_IGNORE_J1939,              RX_CONN_ABORT_TIMEOUT,              RX_CONN_ABORT_RESOURCES_END,                RX_IGNORE_J1939,            RX_IGNORE_J1939,               RX_IGNORE_J1939,                 RX_IGNORE_J1939 },
/* WAIT_DT */ {                                                UNEXP_RECEIVE_RTS,     RX_IGNORE_J1939,                  RX_IGNORE_J1939,         RX_IGNORE_J1939,      RX_IGNORE_J1939,           RECEIVE_DT,                RX_IGNORE_J1939,                RX_IGNORE_J1939,              TX_CONN_ABORT_TIMEOUT,                          RX_IGNORE_J1939,              TX_CONN_ABORT_RESOURCES_END,                                RX_IGNORE_J1939,      RX_IGNORE_J1939,                 TIMEOUT,                         RX_IGNORE_J1939,                                      RX_IGNORE_J1939,              RX_CONN_ABORT_TIMEOUT,              RX_CONN_ABORT_RESOURCES_END,                RX_IGNORE_J1939,            RX_IGNORE_J1939,               RX_IGNORE_J1939,                 RX_IGNORE_J1939 },
/* RECEIVE_DT */ {                                             UNEXP_RECEIVE_RTS,        TRANSMIT_CTS,                  RX_IGNORE_J1939,         RX_IGNORE_J1939,              WAIT_DT,      RX_IGNORE_J1939,        TRANSMIT_END_OF_MSG_ACK,                RX_IGNORE_J1939,                    RX_IGNORE_J1939,                          RX_IGNORE_J1939,              TX_CONN_ABORT_RESOURCES_END,                                RX_IGNORE_J1939,      RX_IGNORE_J1939,                 TIMEOUT,                         RX_IGNORE_J1939,                                      RX_IGNORE_J1939,              RX_CONN_ABORT_TIMEOUT,              RX_CONN_ABORT_RESOURCES_END,                RX_IGNORE_J1939,            RX_IGNORE_J1939,               RX_IGNORE_J1939,                 RX_IGNORE_J1939 },
/* TIMEOUT */ {                                                UNEXP_RECEIVE_RTS,     RX_IGNORE_J1939,                  RX_IGNORE_J1939,         RX_IGNORE_J1939,      RX_IGNORE_J1939,      RX_IGNORE_J1939,                RX_IGNORE_J1939,                RX_IGNORE_J1939,              TX_CONN_ABORT_TIMEOUT,                          RX_IGNORE_J1939,                          RX_IGNORE_J1939,                                RX_IGNORE_J1939,      RX_IGNORE_J1939,         RX_IGNORE_J1939,                         RX_IGNORE_J1939,                                      RX_IGNORE_J1939,              RX_CONN_ABORT_TIMEOUT,              RX_CONN_ABORT_RESOURCES_END,                RX_IGNORE_J1939,            RX_IGNORE_J1939,               RX_IGNORE_J1939,                 RX_IGNORE_J1939 },
/* RX_ERROR */ {                                               UNEXP_RECEIVE_RTS,     RX_IGNORE_J1939,                  RX_IGNORE_J1939,         RX_IGNORE_J1939,      RX_IGNORE_J1939,      RX_IGNORE_J1939,                RX_IGNORE_J1939,                RX_IGNORE_J1939,                    RX_IGNORE_J1939,                          RX_IGNORE_J1939,              TX_CONN_ABORT_RESOURCES_END,                                RX_IGNORE_J1939,      RX_IGNORE_J1939,                 TIMEOUT,                         RX_IGNORE_J1939,                                      RX_IGNORE_J1939,              RX_CONN_ABORT_TIMEOUT,              RX_CONN_ABORT_RESOURCES_END,                RX_IGNORE_J1939,            RX_IGNORE_J1939,               RX_IGNORE_J1939,                 RX_IGNORE_J1939 },
/* TRANSMIT_END_OF_MSG_ACK */ {                                UNEXP_RECEIVE_RTS,     RX_IGNORE_J1939,                  RX_IGNORE_J1939,         RX_IGNORE_J1939,      RX_IGNORE_J1939,      RX_IGNORE_J1939,                RX_IGNORE_J1939, WAIT_CONFIRM_TX_END_OF_MSG_ACK,                    RX_IGNORE_J1939,                          RX_IGNORE_J1939,              TX_CONN_ABORT_RESOURCES_END,                                RX_IGNORE_J1939,     RX_DEFAULT_J1939,                 TIMEOUT,                         RX_IGNORE_J1939,                                      RX_IGNORE_J1939,                    RX_IGNORE_J1939,                          RX_IGNORE_J1939,                RX_IGNORE_J1939,            RX_IGNORE_J1939,               RX_IGNORE_J1939,                 RX_IGNORE_J1939 },
/* WAIT_CONFIRM_TX_END_OF_MSG_ACK */ {                               RECEIVE_RTS,     RX_IGNORE_J1939,                  RX_IGNORE_J1939,         RX_IGNORE_J1939,      RX_IGNORE_J1939,      RX_IGNORE_J1939,                RX_IGNORE_J1939,                RX_IGNORE_J1939,                    RX_IGNORE_J1939,                          RX_IGNORE_J1939,                          RX_IGNORE_J1939,                                RX_IGNORE_J1939,     RX_DEFAULT_J1939,                 TIMEOUT,                         RX_IGNORE_J1939,                                      RX_IGNORE_J1939,                    RX_IGNORE_J1939,                          RX_IGNORE_J1939,                RX_IGNORE_J1939,            RX_IGNORE_J1939,               RX_IGNORE_J1939,                 RX_IGNORE_J1939 },
/* UNEXP_RECEIVE_RTS */ {                                      UNEXP_RECEIVE_RTS,        TRANSMIT_CTS,                  RX_IGNORE_J1939,         RX_IGNORE_J1939,      RX_IGNORE_J1939,      RX_IGNORE_J1939,                RX_IGNORE_J1939,                RX_IGNORE_J1939,                    RX_IGNORE_J1939,                          RX_IGNORE_J1939,              TX_CONN_ABORT_RESOURCES_END,                                RX_IGNORE_J1939,      RX_IGNORE_J1939,                 TIMEOUT,                         RX_IGNORE_J1939,                                      RX_IGNORE_J1939,              RX_CONN_ABORT_TIMEOUT,              RX_CONN_ABORT_RESOURCES_END,                RX_IGNORE_J1939,            RX_IGNORE_J1939,               RX_IGNORE_J1939,                 RX_IGNORE_J1939 },
/* TX_CONN_ABORT_TIMEOUT */ {                                  UNEXP_RECEIVE_RTS,     RX_IGNORE_J1939,                  RX_IGNORE_J1939,         RX_IGNORE_J1939,      RX_IGNORE_J1939,      RX_IGNORE_J1939,                RX_IGNORE_J1939,                RX_IGNORE_J1939,                    RX_IGNORE_J1939, WAIT_CONFIRM_TRANSMIT_CONN_ABORT_TIMEOUT,                          RX_IGNORE_J1939,                                RX_IGNORE_J1939,      RX_IGNORE_J1939,                 TIMEOUT,                         RX_IGNORE_J1939,                                      RX_IGNORE_J1939,                    RX_IGNORE_J1939,                          RX_IGNORE_J1939,                RX_IGNORE_J1939,            RX_IGNORE_J1939,               RX_IGNORE_J1939,                 RX_IGNORE_J1939 },
/* WAIT_CONFIRM_TRANSMIT_CONN_ABORT_TIMEOUT */ {               UNEXP_RECEIVE_RTS,     RX_IGNORE_J1939,                  RX_IGNORE_J1939,         RX_IGNORE_J1939,      RX_IGNORE_J1939,      RX_IGNORE_J1939,                RX_IGNORE_J1939,                RX_IGNORE_J1939,                    RX_IGNORE_J1939,                          RX_IGNORE_J1939,                          RX_IGNORE_J1939,                                RX_IGNORE_J1939,     RX_DEFAULT_J1939,         RX_IGNORE_J1939,                         RX_IGNORE_J1939,                                      RX_IGNORE_J1939,                    RX_IGNORE_J1939,                          RX_IGNORE_J1939,                RX_IGNORE_J1939,            RX_IGNORE_J1939,               RX_IGNORE_J1939,                 RX_IGNORE_J1939 },
/* TX_CONN_ABORT_RESOURCES_END */ {                            UNEXP_RECEIVE_RTS,     RX_IGNORE_J1939,                  RX_IGNORE_J1939,         RX_IGNORE_J1939,      RX_IGNORE_J1939,      RX_IGNORE_J1939,                RX_IGNORE_J1939,                RX_IGNORE_J1939,                    RX_IGNORE_J1939,                          RX_IGNORE_J1939,                          RX_IGNORE_J1939, WAIT_CONFIRM_TRANSMIT_CONN_ABORT_RESOURCES_END,      RX_IGNORE_J1939,                 TIMEOUT,                         RX_IGNORE_J1939,                                      RX_IGNORE_J1939,                    RX_IGNORE_J1939,                          RX_IGNORE_J1939,                RX_IGNORE_J1939,            RX_IGNORE_J1939,               RX_IGNORE_J1939,                 RX_IGNORE_J1939 },
/* WAIT_CONFIRM_TRANSMIT_CONN_ABORT_RESOURCES_END */ {         UNEXP_RECEIVE_RTS,     RX_IGNORE_J1939,                  RX_IGNORE_J1939,         RX_IGNORE_J1939,      RX_IGNORE_J1939,      RX_IGNORE_J1939,                RX_IGNORE_J1939,                RX_IGNORE_J1939,                    RX_IGNORE_J1939,                          RX_IGNORE_J1939,                          RX_IGNORE_J1939,                                RX_IGNORE_J1939,     RX_DEFAULT_J1939,         RX_IGNORE_J1939,                         RX_IGNORE_J1939,                                      RX_IGNORE_J1939,                    RX_IGNORE_J1939,                          RX_IGNORE_J1939,                RX_IGNORE_J1939,            RX_IGNORE_J1939,               RX_IGNORE_J1939,                 RX_IGNORE_J1939 },
/* TRANSMIT_CONN_ABORT_SESSION_SETUP_EARLY */ {                  RX_IGNORE_J1939,     RX_IGNORE_J1939,                  RX_IGNORE_J1939,         RX_IGNORE_J1939,      RX_IGNORE_J1939,      RX_IGNORE_J1939,                RX_IGNORE_J1939,                RX_IGNORE_J1939,                    RX_IGNORE_J1939,                          RX_IGNORE_J1939,                          RX_IGNORE_J1939,                                RX_IGNORE_J1939,      RX_IGNORE_J1939,         RX_IGNORE_J1939,                         RX_IGNORE_J1939, WAIT_CONFIRM_TRANSMIT_CONN_ABORT_SESSION_SETUP_EARLY,                    RX_IGNORE_J1939,                          RX_IGNORE_J1939,                RX_IGNORE_J1939,            RX_IGNORE_J1939,               RX_IGNORE_J1939,                 RX_IGNORE_J1939 },
/* WAIT_CONFIRM_TRANSMIT_CONN_ABORT_SESSION_SETUP_EARLY */ {     RX_IGNORE_J1939,     RX_IGNORE_J1939,                  RX_IGNORE_J1939,         RX_IGNORE_J1939,      RX_IGNORE_J1939,      RX_IGNORE_J1939,                RX_IGNORE_J1939,                RX_IGNORE_J1939,                    RX_IGNORE_J1939,                          RX_IGNORE_J1939,                          RX_IGNORE_J1939,                                RX_IGNORE_J1939,     RX_DEFAULT_J1939,         RX_IGNORE_J1939,                         RX_IGNORE_J1939,                                      RX_IGNORE_J1939,                    RX_IGNORE_J1939,                          RX_IGNORE_J1939,                RX_IGNORE_J1939,            RX_IGNORE_J1939,               RX_IGNORE_J1939,                 RX_IGNORE_J1939 },
/* RX_CONN_ABORT_TIMEOUT */ {                                  UNEXP_RECEIVE_RTS,     RX_IGNORE_J1939,                  RX_IGNORE_J1939,         RX_IGNORE_J1939,      RX_IGNORE_J1939,      RX_IGNORE_J1939,                RX_IGNORE_J1939,                RX_IGNORE_J1939,                    RX_IGNORE_J1939,                          RX_IGNORE_J1939,                          RX_IGNORE_J1939,                                RX_IGNORE_J1939,     RX_DEFAULT_J1939,         RX_IGNORE_J1939,                         RX_IGNORE_J1939,                                      RX_IGNORE_J1939,                    RX_IGNORE_J1939,                          RX_IGNORE_J1939,                RX_IGNORE_J1939,            RX_IGNORE_J1939,               RX_IGNORE_J1939,                 RX_IGNORE_J1939 },
/* RX_CONN_ABORT_RESOURCES_END */ {                            UNEXP_RECEIVE_RTS,     RX_IGNORE_J1939,                  RX_IGNORE_J1939,         RX_IGNORE_J1939,      RX_IGNORE_J1939,      RX_IGNORE_J1939,                RX_IGNORE_J1939,                RX_IGNORE_J1939,                    RX_IGNORE_J1939,                          RX_IGNORE_J1939,                          RX_IGNORE_J1939,                                RX_IGNORE_J1939,     RX_DEFAULT_J1939,         RX_IGNORE_J1939,                         RX_IGNORE_J1939,                                      RX_IGNORE_J1939,                    RX_IGNORE_J1939,                          RX_IGNORE_J1939,                RX_IGNORE_J1939,            RX_IGNORE_J1939,               RX_IGNORE_J1939,                 RX_IGNORE_J1939 },
/* RECEIVE_FIRST_BAM */ {                                        RX_IGNORE_J1939,     RX_IGNORE_J1939,                  RX_IGNORE_J1939,         RX_IGNORE_J1939,      RX_IGNORE_J1939,      RX_IGNORE_J1939,                RX_IGNORE_J1939,                RX_IGNORE_J1939,                    RX_IGNORE_J1939,                          RX_IGNORE_J1939,                          RX_IGNORE_J1939,                                RX_IGNORE_J1939,      RX_IGNORE_J1939,         RX_IGNORE_J1939,                         RX_IGNORE_J1939,                                      RX_IGNORE_J1939,                    RX_IGNORE_J1939,                          RX_IGNORE_J1939,                RX_IGNORE_J1939,              WAIT_DATA_BAM,               RX_IGNORE_J1939,             TIMEOUT_RECEIVE_BAM },
/* WAIT_DATA_BAM */ {                                            RX_IGNORE_J1939,     RX_IGNORE_J1939,                  RX_IGNORE_J1939,         RX_IGNORE_J1939,      RX_IGNORE_J1939,      RX_IGNORE_J1939,                RX_IGNORE_J1939,                RX_IGNORE_J1939,                    RX_IGNORE_J1939,                          RX_IGNORE_J1939,                          RX_IGNORE_J1939,                                RX_IGNORE_J1939,      RX_IGNORE_J1939,         RX_IGNORE_J1939,                         RX_IGNORE_J1939,                                      RX_IGNORE_J1939,                    RX_IGNORE_J1939,                          RX_IGNORE_J1939,                RX_IGNORE_J1939,            RX_IGNORE_J1939,              RECEIVE_DATA_BAM,             TIMEOUT_RECEIVE_BAM },
/* RECEIVE_DATA_BAM */ {                                         RX_IGNORE_J1939,     RX_IGNORE_J1939,                  RX_IGNORE_J1939,         RX_IGNORE_J1939,      RX_IGNORE_J1939,      RX_IGNORE_J1939,                RX_IGNORE_J1939,                RX_IGNORE_J1939,                    RX_IGNORE_J1939,                          RX_IGNORE_J1939,                          RX_IGNORE_J1939,                                RX_IGNORE_J1939,      RX_IGNORE_J1939,         RX_IGNORE_J1939,                         RX_IGNORE_J1939,                                      RX_IGNORE_J1939,                    RX_IGNORE_J1939,                          RX_IGNORE_J1939,                RX_IGNORE_J1939,              WAIT_DATA_BAM,               RX_IGNORE_J1939,             TIMEOUT_RECEIVE_BAM },
/* TIMEOUT_RECEIVE_BAM */ {                                      RX_IGNORE_J1939,     RX_IGNORE_J1939,                  RX_IGNORE_J1939,         RX_IGNORE_J1939,      RX_IGNORE_J1939,      RX_IGNORE_J1939,                RX_IGNORE_J1939,                RX_IGNORE_J1939,                    RX_IGNORE_J1939,                          RX_IGNORE_J1939,                          RX_IGNORE_J1939,                                RX_IGNORE_J1939,     RX_DEFAULT_J1939,         RX_IGNORE_J1939,                         RX_IGNORE_J1939,                                      RX_IGNORE_J1939,                    RX_IGNORE_J1939,                          RX_IGNORE_J1939,                RX_IGNORE_J1939,            RX_IGNORE_J1939,               RX_IGNORE_J1939,                 RX_IGNORE_J1939 }
};


/*!
\brief short description

full description

\param[in]
*/
static enum j1939_rx_state get_rx_j1939_state(struct j1939_tp_s* instance);

/*!
\brief short description

full description

\param[in]
*/
static void set_rx_j1939_signal(struct j1939_tp_s* instance, enum j1939_rx_signal signal);

#endif /* J1939_RX_FSM_PRIVATE_H */
