#include "can_pt_rx_vars.h"
#include "can_frame_structure.h"
extern uint32 count_TCU_R932_5;
extern struct can_message_s TCU_R932_5_rx_mes;
extern TCU_R932_5 TCU_R932_5_frame;
extern uint32 count_TCU_R932_4;
extern struct can_message_s TCU_R932_4_rx_mes;
extern TCU_R932_4 TCU_R932_4_frame;
extern uint32 count_TCU_R932_3;
extern struct can_message_s TCU_R932_3_rx_mes;
extern TCU_R932_3 TCU_R932_3_frame;
extern uint32 count_TCU_R932_2;
extern struct can_message_s TCU_R932_2_rx_mes;
extern TCU_R932_2 TCU_R932_2_frame;
extern uint32 count_HVC_HV_Status_Msg;
extern struct can_message_s HVC_HV_Status_Msg_rx_mes;
extern HVC_HV_Status_Msg HVC_HV_Status_Msg_frame;
extern uint32 count_Diag_To_ECU;
extern struct can_message_s Diag_To_ECU_rx_mes;
extern Diag_To_ECU Diag_To_ECU_frame;
extern uint32 count_CDA_11;
extern struct can_message_s CDA_11_rx_mes;
extern CDA_11 CDA_11_frame;
extern uint32 count_VAU_EMS_Hash_Immo_RESP;
extern struct can_message_s VAU_EMS_Hash_Immo_RESP_rx_mes;
extern VAU_EMS_Hash_Immo_RESP VAU_EMS_Hash_Immo_RESP_frame;
extern uint32 count_TCU_R932_1;
extern struct can_message_s TCU_R932_1_rx_mes;
extern TCU_R932_1 TCU_R932_1_frame;
extern uint32 count_SAS_Standard;
extern struct can_message_s SAS_Standard_rx_mes;
extern SAS_Standard SAS_Standard_frame;
extern uint32 count_EPB_Status;
extern struct can_message_s EPB_Status_rx_mes;
extern EPB_Status EPB_Status_frame;
extern uint32 count_Diag_Functional_FromPT;
extern struct can_message_s Diag_Functional_FromPT_rx_mes;
extern Diag_Functional_FromPT Diag_Functional_FromPT_frame;
extern uint32 count_DMS_01;
extern struct can_message_s DMS_01_rx_mes;
extern DMS_01 DMS_01_frame;
extern uint32 count_CCU_MSG3;
extern struct can_message_s CCU_MSG3_rx_mes;
extern CCU_MSG3 CCU_MSG3_frame;
extern uint32 count_CCU_HVC_Req_Msg;
extern struct can_message_s CCU_HVC_Req_Msg_rx_mes;
extern CCU_HVC_Req_Msg CCU_HVC_Req_Msg_frame;
extern uint32 count_BCM_VEH_STATE;
extern struct can_message_s BCM_VEH_STATE_rx_mes;
extern BCM_VEH_STATE BCM_VEH_STATE_frame;
extern uint32 count_BCM_Powertrain;
extern struct can_message_s BCM_Powertrain_rx_mes;
extern BCM_Powertrain BCM_Powertrain_frame;
extern uint32 count_BCM_EEM;
extern struct can_message_s BCM_EEM_rx_mes;
extern BCM_EEM BCM_EEM_frame;
extern uint32 count_ACU_01;
extern struct can_message_s ACU_01_rx_mes;
extern ACU_01 ACU_01_frame;
