#include "can_hv_rx_vars.h"
#include "can_frame_structure.h"
extern uint32 count_Hyb_Sys_INV_05;
extern struct can_message_s Hyb_Sys_INV_05_rx_mes;
extern Hyb_Sys_INV_05 Hyb_Sys_INV_05_frame;
extern uint32 count_Hyb_Sys_INV_04;
extern struct can_message_s Hyb_Sys_INV_04_rx_mes;
extern Hyb_Sys_INV_04 Hyb_Sys_INV_04_frame;
extern uint32 count_Hyb_Sys_INV_03;
extern struct can_message_s Hyb_Sys_INV_03_rx_mes;
extern Hyb_Sys_INV_03 Hyb_Sys_INV_03_frame;
extern uint32 count_Hyb_Sys_INV_02;
extern struct can_message_s Hyb_Sys_INV_02_rx_mes;
extern Hyb_Sys_INV_02 Hyb_Sys_INV_02_frame;
extern uint32 count_Hyb_Sys_INV_01;
extern struct can_message_s Hyb_Sys_INV_01_rx_mes;
extern Hyb_Sys_INV_01 Hyb_Sys_INV_01_frame;
extern uint32 count_Hyb_Sys_DC_02;
extern struct can_message_s Hyb_Sys_DC_02_rx_mes;
extern Hyb_Sys_DC_02 Hyb_Sys_DC_02_frame;
extern uint32 count_Hyb_Sys_DC_01;
extern struct can_message_s Hyb_Sys_DC_01_rx_mes;
extern Hyb_Sys_DC_01 Hyb_Sys_DC_01_frame;
extern uint32 count_Hyb_Sys_BMS_04;
extern struct can_message_s Hyb_Sys_BMS_04_rx_mes;
extern Hyb_Sys_BMS_04 Hyb_Sys_BMS_04_frame;
extern uint32 count_Hyb_Sys_BMS_03;
extern struct can_message_s Hyb_Sys_BMS_03_rx_mes;
extern Hyb_Sys_BMS_03 Hyb_Sys_BMS_03_frame;
extern uint32 count_Hyb_Sys_BMS_02;
extern struct can_message_s Hyb_Sys_BMS_02_rx_mes;
extern Hyb_Sys_BMS_02 Hyb_Sys_BMS_02_frame;
extern uint32 count_Hyb_Sys_BMS_01;
extern struct can_message_s Hyb_Sys_BMS_01_rx_mes;
extern Hyb_Sys_BMS_01 Hyb_Sys_BMS_01_frame;
extern uint32 count_Diag_From_INC;
extern struct can_message_s Diag_From_INC_rx_mes;
extern Diag_From_INC Diag_From_INC_frame;
extern uint32 count_Diag_From_BMS;
extern struct can_message_s Diag_From_BMS_rx_mes;
extern Diag_From_BMS Diag_From_BMS_frame;
extern uint32 count_BSC6VAL2;
extern struct can_message_s BSC6VAL2_rx_mes;
extern BSC6VAL2 BSC6VAL2_frame;
extern uint32 count_BSC6VAL1;
extern struct can_message_s BSC6VAL1_rx_mes;
extern BSC6VAL1 BSC6VAL1_frame;
